# .github/FUNDING.yml
github: false
patreon: false
open_collective: false
ko_fi: false
buy_me_a_coffee: false
polar: false

# Custom sponsorship links
custom:
  - "https://giveth.io/project/qsbench"
  - "https://ko-fi.com/qsbench"
  - "USDT (TRC20): TQcgRru2yjPjCtqDkHYMr5vsRcejbpk1zG"
  - "TON: UQCPgjp_yK9c-Wn_708xDR_DZ6Pi6DnfqXfQRqQcc9W7xD0f"
