services:
  quantum-gen:
    build: .
    container_name: qsb_generator
    working_dir: /app
    gpus: all
    shm_size: "8gb"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./out:/app/out
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      QISKIT_AER_DEBUG: "1"
      PYTHONUNBUFFERED: "1"
    command: ["sleep", "infinity"]